GET http://localhost:3100/loki/api/v1/label/level/values


###
GET https://menuq.arknishinvent.com/api/health

###
GET http://localhost:8080/api/menuq/WMiNOcc6j4aRbAkpD4unBsM7rOG3

###
GET http://menuq.arknishinvent.com/api/menu/RX00035

###
GET http://menuq.arknishinvent.com/api/menuq/byId/RX00003

###
GET http://13.234.225.202:8080/api/health

###
GET http://menuq.arknishinvent.com/api/test

###
GET https://menuq.arknishinvent.com/api/menuq/pGx6DnxdBuPIgDS6mAjK11dg0tC2

###
GET http://localhost:8080/api/menu/RX00001

###
GET https://menuq.arknishinvent.com/api/menu/RX00002

###
GET http://localhost:8080/api/menu/item/67aadaa454641ff4345fb9d6

###
GET http://localhost:8080/api/menuq/

###
PATCH http://localhost:8080/api/menu/availability/67aadaa454641ff4345fb9d6
Content-Type: application/json

{
  "available": false
}

###
PATCH http://localhost:8080/api/menu/prepTime/67aadaa454641ff4345fb9d8
Content-Type: application/json

{
  "prepTime": 20
}

###
POST http://localhost:8080/api/menuq
Content-Type: application/json

{
  "firebaseUid": "user_123",
  "email": "health@example.com",
  "phone": "9876543210",
  "restaurantName": "Tasty Bites",
  "restaurantAddress": "123 Main Street, City",
  "noOfSeats": 0
//  "restaurantCategory": "Cafe",
//  "cuisineType": ["Italian", "Indian"],
}

###
GET http://localhost:8080/api/menu/RX00045

### Update all operating hours for a restaurant
PUT https://menuq.arknishinvent.com/api/menuq/b3r6hSN70OXMQkMAHT1h5QeybIk2/hours
Content-Type: application/json

{
  "operatingHours": [
    { "day": "Monday", "hours": "11:00 AM - 5:00 PM" },
    { "day": "Tuesday", "hours": "9:00 AM - 5:00 PM" },
    { "day": "Wednesday", "hours": "9:00 AM - 5:00 PM" },
    { "day": "Thursday", "hours": "9:00 AM - 5:00 PM" },
    { "day": "Friday", "hours": "9:00 AM - 6:00 PM" },
    { "day": "Saturday", "hours": "10:00 AM - 4:00 PM" },
    { "day": "Sunday", "hours": "Closed" }
  ]
}

### Update operating hours for a specific day
PATCH https://menuq.arknishinvent.com/api/menuq/b3r6hSN70OXMQkMAHT1h5QeybIk2/hours
Content-Type: application/json

{
  "day": "Tuesday",
  "hours": "8:00 AM - 6:00 PM"
}

### Delete operating hours for a specific day
DELETE https://menuq.arknishinvent.com/api/menuq/b3r6hSN70OXMQkMAHT1h5QeybIk2/hours/Monday

###
DELETE https://menuq.arknishinvent.com/api/menuq/pGx6DnxdBuPIgDS6mAjK11dg0tC2/hours/Sunday

### Update restaurant status to open
PATCH https://menuq.arknishinvent.com/api/menuq/b3r6hSN70OXMQkMAHT1h5QeybIk2/status
Content-Type: application/json

{
  "resOpen": false
}

