GET http://localhost:3000/menuq/WMiNOcc6j4aRbAkpD4unBsM7rOG3

###
GET http://localhost:3000/menuq/byId/RX00001

###
GET http://localhost:3000/menu/RX00001

###
GET http://localhost:3000/menu/RX00028

###
GET http://localhost:3000/menu/item/67aadaa454641ff4345fb9d6

###
GET http://localhost:3000/menuq/

###
PATCH http://localhost:3000/menu/availability/67aadaa454641ff4345fb9d6
Content-Type: application/json

{
  "available": false
}
###
POST http://localhost:3000/menuq
Content-Type: application/json

{
  "firebaseUid": "user_123",
  "email": "test@example.com",
  "phone": "9876543210",
  "restaurantName": "Tasty Bites",
  "restaurantAddress": "123 Main Street, City",
  "noOfSeats": 0
//  "restaurantCategory": "Cafe",
//  "cuisineType": ["Italian", "Indian"],
}

###
GET http://localhost:3000/menu/RX00028