import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Get Started' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('archanakmitt@gmail.com');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('9916880339');
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('aA@14389');
  await page.getByRole('button', { name: 'Show password' }).first().click();
  await page.getByRole('button', { name: 'Hide password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('aA@14389');
  await page.getByRole('textbox', { name: 'Restaurant Name' }).click();
  await page.getByRole('textbox', { name: 'Restaurant Name' }).fill('AKG\'s');
  await page.getByRole('textbox', { name: 'Restaurant Address' }).click();
  await page.getByRole('textbox', { name: 'Restaurant Name' }).click();
  await page.getByRole('textbox', { name: 'Restaurant Address' }).click();
  await page.getByRole('textbox', { name: 'Restaurant Address' }).fill('Mysore');
  await page.getByRole('spinbutton', { name: 'Number of Seats' }).click();
  await page.getByRole('spinbutton', { name: 'Number of Seats' }).fill('50');
  await page.getByRole('spinbutton', { name: 'Number of Seats' }).click();
  await page.getByLabel('Restaurant Category').selectOption('Fine Dining');
  await page.getByRole('button', { name: 'Create account' }).click();
  await page.getByRole('link', { name: 'Log In' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('aphorismedgetech.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('aA@14389');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('aphorismedgetech@gmail.com');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Manage Menu' }).click();
  await page.getByRole('link', { name: 'Add Menu Item' }).click();
  await page.getByRole('link', { name: 'Edit Profile' }).click();
  await page.getByRole('link', { name: 'Manage Menu' }).click();
  await page.getByRole('link', { name: 'Add Menu Item' }).click();
  await page.getByRole('textbox', { name: 'Item Name' }).click();
  await page.getByRole('textbox', { name: 'Item Name' }).fill('bath');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('ahgfusahgeif');
  await page.getByRole('combobox').selectOption('Main Course');
  await page.locator('div').filter({ hasText: /^Non-vegetarian$/ }).getByRole('button').click();
  await page.getByPlaceholder('Base Price').click();
  await page.getByPlaceholder('Base Price').fill('50');
  await page.getByRole('button', { name: 'Add Variant' }).click();
  await page.getByRole('textbox', { name: 'Variant Name' }).click();
  await page.getByRole('textbox', { name: 'Variant Name' }).fill('bath');
  await page.getByPlaceholder('Price', { exact: true }).click();
  await page.getByPlaceholder('Price', { exact: true }).fill('01');
  await page.getByPlaceholder('Price', { exact: true }).press('ArrowLeft');
  await page.getByPlaceholder('Price', { exact: true }).fill('1');
  await page.getByRole('textbox', { name: 'Add tag' }).click();
  await page.getByRole('textbox', { name: 'Add tag' }).fill('Good');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Add Menu Item' }).click();
  await page.getByRole('link', { name: 'Manage Menu' }).click();
  await page.locator('div').filter({ hasText: 'Logout' }).nth(4).click();
  await page.getByRole('button', { name: 'Log out' }).click();
});