import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('archanakgowda28@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('aA@14389');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Add Menu Item' }).click();
  await page.getByRole('button', { name: '🍽️ Choose from Predefined' }).click();
  await page.getByText('Samosa').click();
  await page.getByRole('button', { name: 'Add Menu Item' }).click();
  await page.getByRole('textbox', { name: 'Item Name' }).click();
  await page.getByRole('textbox', { name: 'Item Name' }).fill('serfserf');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('erfsd');
  await page.getByRole('combobox').selectOption('Drinks');
  await page.getByPlaceholder('Base Price').click();
  await page.getByPlaceholder('Base Price').fill('1000');
  await page.getByRole('button', { name: 'Add Variant' }).click();
  await page.getByRole('textbox', { name: 'Variant Name' }).click();
  await page.getByRole('textbox', { name: 'Variant Name' }).fill('sadfds');
  await page.getByPlaceholder('Price', { exact: true }).click();
  await page.getByPlaceholder('Price', { exact: true }).fill('30');
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByRole('textbox', { name: 'Add On Name' }).click();
  await page.getByRole('textbox', { name: 'Add On Name' }).fill('sdfsdf');
  await page.locator('div').filter({ hasText: /^Add New$/ }).getByPlaceholder('Price').click();
  await page.locator('div').filter({ hasText: /^Add New$/ }).getByPlaceholder('Price').fill('28');
  await page.getByRole('textbox', { name: 'Add tag' }).click();
  await page.getByRole('textbox', { name: 'Add tag' }).fill('dsfsdf');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Add Menu Item' }).click();
  await page.getByRole('link', { name: 'Dashboard New' }).click();
});