import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('archanakgowda28@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('aA@14389');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Add Menu Item' }).click();
  await page.getByRole('textbox', { name: 'Item Name' }).click();
  await page.getByRole('textbox', { name: 'Item Name' }).fill('kaju');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('jhgjuyu');
  await page.getByRole('combobox').selectOption('Desserts');
  await page.locator('div').filter({ hasText: /^Non-vegetarian$/ }).click();
  await page.locator('div').filter({ hasText: /^Non-vegetarian$/ }).getByRole('button').click();
  await page.getByPlaceholder('Base Price').click();
  await page.getByPlaceholder('Base Price').fill('59');
  await page.getByRole('button', { name: 'Add Variant' }).click();
  await page.getByRole('textbox', { name: 'Variant Name' }).click();
  await page.getByRole('textbox', { name: 'Variant Name' }).fill('ghfqhwge');
  await page.getByPlaceholder('Price', { exact: true }).click();
  await page.getByPlaceholder('Price', { exact: true }).fill('10');
  await page.getByRole('textbox', { name: 'Add tag' }).click();
  await page.getByRole('textbox', { name: 'Add tag' }).fill('rytert');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByRole('textbox', { name: 'Add On Name' }).click();
  await page.getByRole('textbox', { name: 'Add On Name' }).fill('tgrweur');
  await page.locator('div').filter({ hasText: /^Add New$/ }).getByPlaceholder('Price').click();
  await page.locator('div').filter({ hasText: /^Add New$/ }).getByPlaceholder('Price').fill('27');
  await page.getByRole('button', { name: 'Add Menu Item' }).click();
  await page.getByRole('button', { name: '🍽️ Choose from Predefined' }).click();
  await page.getByText('Spring Rolls').click();
  await page.getByRole('button', { name: 'Add Menu Item' }).click();
  await page.getByRole('link', { name: 'Manage Menu' }).click();
});