import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Get Started' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('archanakgowda22@gmail.com');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('9916880339');
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('aA214389');
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('aA@14389');
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('button', { name: 'Show password' }).nth(1).click();
  await page.getByRole('button', { name: 'Show password' }).click();
  await page.getByRole('textbox', { name: 'Restaurant Name' }).click();
  await page.getByRole('textbox', { name: 'Restaurant Name' }).fill('Arch');
  await page.getByRole('textbox', { name: 'Restaurant Address' }).click();
  await page.getByRole('textbox', { name: 'Restaurant Address' }).fill('Banglore');
  await page.getByRole('spinbutton', { name: 'Number of Seats' }).click();
  await page.getByRole('spinbutton', { name: 'Number of Seats' }).fill('29');
  await page.getByLabel('Restaurant Category').selectOption('Casual Dining');
  await page.getByRole('button', { name: 'Create account' }).click();
  await page.getByRole('link', { name: 'Manage Menu' }).click();
  await page.getByRole('link', { name: 'Add Menu Item' }).click();
  await page.getByRole('textbox', { name: 'Item Name' }).click();
  await page.getByRole('textbox', { name: 'Item Name' }).fill('samber');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('sdfdhg');
  await page.getByRole('combobox').selectOption('Main Course');
  await page.locator('div').filter({ hasText: /^Non-vegetarian$/ }).getByRole('button').click();
  await page.getByPlaceholder('Base Price').click();
  await page.getByPlaceholder('Base Price').fill('29');
  await page.getByRole('button', { name: 'Add Variant' }).click();
  await page.getByRole('textbox', { name: 'Variant Name' }).click();
  await page.getByRole('textbox', { name: 'Variant Name' }).fill('edly');
  await page.getByPlaceholder('Price', { exact: true }).click();
  await page.getByPlaceholder('Price', { exact: true }).press('ArrowLeft');
  await page.getByPlaceholder('Price', { exact: true }).fill('10');
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByRole('textbox', { name: 'Add On Name' }).dblclick();
  await page.getByRole('textbox', { name: 'Add On Name' }).fill('chetni');
  await page.getByRole('textbox', { name: 'Add tag' }).click();
  await page.getByRole('textbox', { name: 'Add tag' }).fill('good');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Add Menu Item' }).click();
  await page.getByRole('link', { name: 'Edit Profile' }).click();
  await page.getByPlaceholder('Number of Seats').click();
  await page.getByPlaceholder('Number of Seats').fill('26');
  await page.getByRole('button', { name: 'Update Profile' }).click();
  await page.getByRole('link', { name: 'Manage Menu' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByPlaceholder('Base Price').click();
  await page.getByPlaceholder('Base Price').fill('30');
  await page.getByRole('textbox', { name: 'Add tag' }).click();
  await page.getByRole('textbox', { name: 'Add tag' }).fill('bvest');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await page.getByRole('button', { name: 'Update Menu Item' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button', { name: 'View Details' }).click();
  await page.locator('div').filter({ hasText: /^- mins$/ }).getByRole('button').click();
  await page.getByPlaceholder('Minutes').click();
  await page.getByPlaceholder('Minutes').fill('20');
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByRole('button', { name: 'Show Less' }).click();
  await page.getByRole('link', { name: 'Dashboard New' }).click();
  await page.locator('div').filter({ hasText: 'Logout' }).nth(4).click();
  await page.getByRole('button', { name: 'Log out' }).click();
});